on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        go-version: [1.15.x]
    #     os: [ubuntu-latest, macos-latest, windows-latest]
    # runs-on: ${{ matrix.os }}
    steps:
      - name: Set Golang shared lib directory for GH Actions
        run: |
          echo "LD_LIBRARY_PATH=/tmp" >> $GITHUB_ENV
          echo "PACT_GO_LIB_DOWNLOAD_PATH=/tmp" >> $GITHUB_ENV
          echo "LOG_LEVEL=trace" >> $GITHUB_ENV
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.5
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: make
        env:
          ACCEPTANCE_PACT_BROKER_TOKEN: "${{ secrets.ACCEPTANCE_PACT_BROKER_TOKEN }}"
          PACTFLOW_PACT_BROKER_TOKEN: "${{ secrets.PACTFLOW_PACT_BROKER_TOKEN }}"
          PACTFLOW_PACT_BROKER_BASE_URL: "${{ secrets.PACTFLOW_PACT_BROKER_BASE_URL }}"
